core/urls.py
from django.urls import path
from .views import *


app_name = 'core'

urlpatterns = [
    path('', base, name='base'),
    path('calendar/', calendar, name='calendar'),
    path('info/<int:id>/', info, name='info'),
    path('reviews/', review, name='reviews'),
    path('review/create/', review_create, name='review_create'),
]

xirurgia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


# urlpatterns = [
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
#     path('', include('core.urls')),
#     path('ckeditor/', include('ckeditor_uploader.urls')),
# ]

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.db import models


def validate_only_one_instance(obj):
    model = obj.__class__
    if (model.objects.count() > 0 and
            obj.id != model.objects.get().id):
        raise ValidationError("Դուք կարող եք ստեղծել միայն մեկ" % model.__name__)


class SectionGeneral(models.Model):
    name_hy = models.CharField(max_length=30, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (hy)')
    name_ru = models.CharField(max_length=30, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (ru)')
    name_en = models.CharField(max_length=30, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (en)')
    info_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Պաշտոն և այլն (hy)')
    info_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Պաշտոն և այլն (ru)')
    info_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Պաշտոն և այլն (en)')
    phone = models.CharField(max_length=20, db_index=True, verbose_name='Հեռախոսահամար')
    img = models.ImageField(upload_to='general', verbose_name='Նկար')

    class Meta:
        verbose_name = 'Բժշկի անձնական տվյալներ'
        verbose_name_plural = 'Բժշկի անձնական տվյալներ'

    def __str__(self):
        return self.name_hy

    def clean(self):
        validate_only_one_instance(self)


class GeneralServices(models.Model):
    name_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (hy)')
    name_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (ru)')
    name_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (en)')
    body_hy = RichTextField(max_length=7000, blank=True, verbose_name='Ծառայության մասին (hy)')
    body_ru = RichTextField(max_length=7000, blank=True, verbose_name='Ծառայության մասին (ru)')
    body_en = RichTextField(max_length=7000, blank=True, verbose_name='Ծառայության մասին (en)')
    img = models.ImageField(upload_to='services', verbose_name='Ծառայության նկար')

    class Meta:
        verbose_name = 'Գովազդային ծառայություն'
        verbose_name_plural = 'Գովազդային ծառայություն'

    def __str__(self):
        return self.name_hy

    def clean(self):
        validate_only_one_instance(self)


class Services(models.Model):
    name_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (hy)')
    name_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (ru)')
    name_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (en')
    body_hy = RichTextField(max_length=3000, blank=True, verbose_name='Ծառայության մասին (hy)')
    body_ru = RichTextField(max_length=3000, blank=True, verbose_name='Ծառայության մասին (ru)')
    body_en = RichTextField(max_length=3000, blank=True, verbose_name='Ծառայության մասին (en)')
    img = models.ImageField(upload_to='services', verbose_name='Ծառայության նկար')

    class Meta:
        verbose_name = 'Ծառայություններ'
        verbose_name_plural = 'Ծառայություններ'

    def __str__(self):
        return self.name_hy


class AboutMe(models.Model):
    img = models.ImageField(upload_to='about', verbose_name='Մեր մասին նկար')
    body_l_hy = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (hy) ձախ')
    body_l_ru = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (ru) ձախ')
    body_l_en = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (en) ձախ')
    body_r_hy = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (hy) աջ')
    body_r_ru = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (ru) աջ')
    body_r_en = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (en) աջ')

    class Meta:
        verbose_name = 'Բժշկի մասին'
        verbose_name_plural = 'Բժշկի մասին'

    def __str__(self):
        return self.body_l_hy

    def clean(self):
        validate_only_one_instance(self)


class Works(models.Model):
    img = models.ImageField(upload_to='works/%Y/%m/%d', blank=True, verbose_name='Մեր գործերը նկար')
    url = models.CharField(max_length=1000, blank=True, verbose_name='Մեր գործերը լինք')

    class Meta:
        ordering = ['-id']
        verbose_name = 'Կատարված աշխատանք'
        verbose_name_plural = 'Կատարված աշխատանքներ'


class Review(models.Model):
    content_hy = models.TextField(max_length=4000, blank=True, verbose_name='Ակնարկներ (hy)')
    content_ru = models.TextField(max_length=4000, blank=True, verbose_name='Ակնարկներ (ru)')
    content_en = models.TextField(max_length=4000, blank=True, verbose_name='Ակնարկներ (en)')
    name_hy = models.CharField(max_length=40, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (hy)')
    name_ru = models.CharField(max_length=40, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (ru)')
    name_en = models.CharField(max_length=40, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (en)')
    disease_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Բուժված հիվանդությունը (hy)')
    disease_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Բուժված հիվանդությունը (ru)')
    disease_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Բուժված հիվանդությունը (en)')
    published = models.BooleanField(default=False, verbose_name='Հրապարակել')
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Կարծիք'
        verbose_name_plural = 'Կարծիքներ'

    def __str__(self):
        return self.name_hy


class Contacts(models.Model):
    phone = models.CharField(max_length=25, db_index=True, verbose_name='Հեռախոսահամա')
    whatsapp = models.CharField(max_length=30, db_index=True, verbose_name='WhatsApp')
    whatsapp_link = models.CharField(max_length=25, db_index=True, verbose_name='WhatsApp (Առանց '+' և բացատի)')
    viber = models.CharField(max_length=30, db_index=True, verbose_name='Viber')
    viber_link = models.CharField(max_length=25, db_index=True, verbose_name='Viber (Առանց '+' և բացատի)')
    fb = models.CharField(max_length=100, db_index=True, verbose_name='Facebook')
    mail = models.CharField(max_length=50, db_index=True, verbose_name='Mail')
    address_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հասցե (hy)')
    address_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հասցե (ru)')
    address_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հասցե (en)')

    class Meta:
        verbose_name = 'Կոնտակտ'
        verbose_name_plural = 'Կոնտակտներ'

    def __str__(self):
        return self.phone

    def clean(self):
        validate_only_one_instance(self)


class Information(models.Model):
    name_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հիվանդության անունը (hy)')
    name_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հիվանդության անունը (ru)')
    name_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հիվանդության անունը (en)')
    info_hy = RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (hy)')
    info_ru = RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (ru)')
    info_en = RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (en)')

    class Meta:
        verbose_name = 'Հիվանդությունների մասին և այլն'
        verbose_name_plural = 'Հիվանդությունների մասին և այլն'

    def __str__(self):
        return self.name_hy

TIME_CHOICES = [
    ('10:00-10:30', '10:00-10:30'),
    ('10:30-11:00', '10:30-11:00'),
    ('11:00-11:30', '11:00-11:30'),
    ('11:30-12:00', '11:30-12:00'),
    ('12:00-12:30', '12:00-12:30'),
    ('12:30-13:00', '12:30-13:00'),
    ('13:00-13:30', '13:00-13:30'),
    ('13:30-14:00', '13:30-14:00'),
    ('14:00-14:30', '14:00-14:30'),
    ('14:30-15:00', '14:30-15:00'),
    ('15:00-15:30', '15:00-15:30'),
    ('15:30-16:00', '15:30-16:00'),
    ('16:00-16:30', '16:00-16:30'),
    ('16:30-17:00', '16:30-17:00'),
]


class CheckedDate(models.Model):
    date = models.DateField(auto_now_add=False, blank=True, verbose_name='Ամիս ամսաթիվ')

    class Meta:
        verbose_name = 'Աշխատանքային օր'
        verbose_name_plural = 'Աշխատանքային օրեր'

    def __str__(self):
        return str(self.date)

class CheckedTime(models.Model):
    TIME_CHOICES = [
        ('10:00-10:30', '10:00-10:30'),
        ('10:30-11:00', '10:30-11:00'),
        ('11:00-11:30', '11:00-11:30'),
        ('11:30-12:00', '11:30-12:00'),
        ('12:00-12:30', '12:00-12:30'),
        ('12:30-13:00', '12:30-13:00'),
        ('13:00-13:30', '13:00-13:30'),
        ('13:30-14:00', '13:30-14:00'),
        ('14:00-14:30', '14:00-14:30'),
        ('14:30-15:00', '14:30-15:00'),
        ('15:00-15:30', '15:00-15:30'),
        ('15:30-16:00', '15:30-16:00'),
        ('16:00-16:30', '16:00-16:30'),
        ('16:30-17:00', '16:30-17:00'),
    ]
    date = models.ForeignKey('CheckedDate', on_delete=models.CASCADE)
    time = models.CharField(max_length=12, choices=TIME_CHOICES, verbose_name='Ժամ')

    class Meta:
        verbose_name = 'Աշխատանքային ժամ'
        verbose_name_plural = 'Աշխատանքային ժամեր'

    def __str__(self):

core/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from .models import *


class ReviewCreateForm(forms.ModelForm):
    # content = forms.CharField(widget=CKEditorWidget(attrs={'placeholder': '* Ակնարկ'}))

    class Meta:
        model = Review
        fields = ['name_hy', 'disease_hy', 'content_hy', 'name_ru', 'disease_ru', 'content_ru', 'name_en', 'disease_en',
                  'content_en']
        exclude = ['published', 'pub_date']
        widgets = {
            'name_hy': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Անուն Ազգանուն', 'required': ''}),
            'name_ru': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Имя Фамилия', 'required': ''}),
            'name_en': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* First name Last name', 'required': ''}),
            'disease_hy': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Բուժված հիվանդությունը', 'required': ''}),
            'disease_ru': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Вылеченная болезнь', 'required': ''}),
            'disease_en': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* The cured disease', 'required': ''}),
            'content_hy': forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'placeholder': '* Ակնարկ'}),
            'content_ru': forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'placeholder': '* Коментария'}),
            'content_en': forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'placeholder': '* Comment'}),
        }

core/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404
# from bs4 import BeautifulSoup, NavigableString, Tag
from pip._vendor.urllib3.connectionpool import xrange

from .models import *
from .forms import *


def base(request):
    general = SectionGeneral.objects.last()
    service = GeneralServices.objects.last()
    services = Services.objects.all()
    about = AboutMe.objects.last()
    works = Works.objects.all()
    reviews = Review.objects.all()
    contacts = Contacts.objects.last()
    information = Information.objects.all()

    context = {
        'general': general,
        'service': service,
        'services': services,
        'about': about,
        'works': works,
        'reviews': reviews,
        'contacts': contacts,
        'information': information,
    }
    return render(request, 'core/core_base.html', context)


def info(request, id=None):
    general = SectionGeneral.objects.last()
    information = Information.objects.all()
    contacts = Contacts.objects.last()
    info = get_object_or_404(Information, id=id)

    context = {
        'information': information,
        'info': info,
        'contacts': contacts,
        'general': general,
    }
    return render(request, 'core/info.html', context)


def review(request):
    general = SectionGeneral.objects.last()
    information = Information.objects.all()
    contacts = Contacts.objects.last()
    reviews = Review.objects.all()

    context = {
        'information': information,
        'reviews': reviews,
        'contacts': contacts,
        'general': general,
    }
    return render(request, 'core/review.html', context)


def review_create(request):
    general = SectionGeneral.objects.last()
    information = Information.objects.all()
    contacts = Contacts.objects.last()
    if request.method == 'POST':
        form = ReviewCreateForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ReviewCreateForm()

    context = {
        'information': information,
        'review': review,
        'contacts': contacts,
        'general': general,
        'form': form,
    }
    return render(request, 'core/review_create.html', context)



def calendar(request):
    today = datetime.date.today().strftime('%Y-%m-%d')
    tomorrow = datetime.date.today() + datetime.timedelta(days=1)
    tomorrow = tomorrow.strftime('%Y-%m-%d')
    nextYear = int(datetime.date.today().year) + 1
    successDays = CheckedDate.objects.all()
    successTimes = CheckedTime.objects.all()

    weekends = []

    dates = []
    times = []
    for sdays in successTimes:
        dates.insert(0, sdays.date)
        times.insert(0, sdays.time)
    #
    # times = iter(times)
    # dates = iter(dates)
    #
    # res = list(zip(dates, times))
    # data = {}
    # for (x, y) in res:
    #     if x in data:
    #         data[x] = data[x] + y
    #     else:
    #         data[x] = y
    #
    # data = {
    #     'labels': data.keys(),
    #     'default': data.values()
    # }


    # print(data)

    minDate = datetime.date(2020, 1, 1)
    maxDate = datetime.date.today() + datetime.timedelta(days=750)
    daygenerator = (minDate + datetime.timedelta(x + 1) for x in xrange((maxDate - minDate).days))
    for day in daygenerator:
        if day.weekday() >= 5:
            weekends.append(str(day.strftime('%Y-%m-%d')))

    if request.method == 'POST':
        sdate = request.POST.get('date')
        stime = request.POST.get('time')
        if sdate and stime is not None:
            a = CheckedDate.objects.filter(date=sdate)
            print(a.first())
            if a.first() is None:
                createCheckedDate = CheckedDate(date=sdate)
                createCheckedDate.save()
            filteredDate = CheckedDate.objects.filter(date=sdate).first()
            createCheckedTime = CheckedTime(time=stime, date_id=filteredDate.id)
            createCheckedTime.save()
    filteredDate = CheckedDate.objects.all()
    for filtered in filteredDate:
        f_id = filtered.id
        b = len(CheckedTime.objects.filter(date_id=f_id))
        if b == 14:
            f_d = CheckedDate.objects.filter(id=f_id).first()
            weekends.append(f_d)
    choices = []
    for choice in dict(CheckedTime.TIME_CHOICES):
        choices.append(choice)

        # print(stime)
        # print(sdata)

    context = {
        'today': today,
        'tomorrow': tomorrow,
        'successDays': successDays,
        'weekends': weekends,
        'nextYear': nextYear,
        'choices': choices,
    }
    return render(request, 'core/calendar/calendar1.html', context)









templates/core/info.html
{% extends 'base.html' %}
{% load static %}
{% block core %}
    <div class="site-section">
        <div class="container">
            <div class="row ">
                {% if LANGUAGE_CODE == 'en' and info.name_en|length > 0 %}
                    <div class="col-12 mb-5 position-relative">
                        <h2 class="section-title text-center mb-5">{{ info.name_en }}</h2>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-10">
                            {{ info.info_en|safe }}
                        </div>
                    </div>
                {% elif LANGUAGE_CODE == 'ru' and info.name_ru|length > 0 %}
                    <div class="col-12 mb-5 position-relative">
                        <h2 class="section-title text-center mb-5">{{ info.name_ru }}</h2>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-10">
                            {{ info.info_ru|safe }}
                        </div>
                    </div>
                {% else %}
                    <div class="col-12 mb-5 position-relative">
                        <h2 class="section-title text-center mb-5">{{ info.name_hy }}</h2>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-10">
                            {{ info.info_hy|safe }}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/review.html
{% extends 'base.html' %}
{% load static i18n %}
{% block core %}
    <section class="site-section" id="review">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-5 position-relative">
                    <h2 class="section-title text-center mb-5">{% trans 'Կարծիքներ' %}</h2>
                    <a class="btn btn-light" href="{% url 'core:review_create' %}">{% trans 'Ավելացնել նորը' %}</a>
                </div>
            </div>
            <div class="row">
                {% for foo in reviews %}
                    <div class="col-12 mt-5">
                        {% if LANGUAGE_CODE == 'en' and info.name_en|length > 0 %}
                            <h3>{{ foo.disease_en }}</h3>
                            <p>{{ foo.content_en|safe }}</p>
                            <div class="row">
                                <div class="col-12">
                                    <cite>&mdash; {{ foo.name_en }}</cite>
                                </div>
                                <div class="col-12">
                                    <cite style="font-size: 10px">{{ foo.pub_date|date:'M d Y' }}</cite>
                                </div>
                            </div>
                        {% elif LANGUAGE_CODE == 'ru' and info.name_ru|length > 0 %}
                            <h3>{{ foo.disease_ru }}</h3>
                            <p>{{ foo.content_ru|safe }}</p>
                            <div class="row">
                                <div class="col-12">
                                    <cite>&mdash; {{ foo.name_ru }}</cite>
                                </div>
                                <div class="col-12">
                                    <cite style="font-size: 10px">{{ foo.pub_date|date:'M d Y' }}</cite>
                                </div>
                            </div>
                        {% else %}
                            <h3>{{ foo.disease_hy }}</h3>
                            <p>{{ foo.content_hy|safe }}</p>
                            <div class="row">
                                <div class="col-12">
                                    <cite>&mdash; {{ foo.name_hy }}</cite>
                                </div>
                                <div class="col-12">
                                    <cite style="font-size: 10px">{{ foo.pub_date|date:'M d Y' }}</cite>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/core/review_create.html
{% extends 'base.html' %}
{% load static i18n %}
{% block core %}
    <section class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-12 mb-5 position-relative">
                    <h2 class="section-title text-center mb-5">{% trans 'Ավելացնել կարծիք' %}</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col--lg-6 col-md-6 col-sm-11 mt-5">
                    <form action="." method="post">
                        {% csrf_token %}
{#                        {{ form.media }}#}
                        {% if LANGUAGE_CODE == 'hy' %}
                            <div class="form-group">
                                {{ form.name_hy }}
                            </div>
                            <div class="form-group">
                                {{ form.disease_hy }}
                            </div>
                            <div class="form-group">
                                {{ form.content_hy }}
                            </div>
                            <div class="form-group">
                                <input class="btn btn-dark" type="submit" value="{% trans 'Ավելացնել' %}">
                            </div>
                        {% elif LANGUAGE_CODE == 'ru' %}
                            <div class="form-group">
                                {{ form.name_ru }}
                            </div>
                            <div class="form-group">
                                {{ form.disease_ru }}
                            </div>
                            <div class="form-group">
                                {{ form.content_ru }}
                            </div>
                            <div class="form-group">
                                <input class="btn btn-dark" type="submit" value="{% trans 'Ավելացնել' %}">
                            </div>
                        {% else %}
                            <div class="form-group">
                                {{ form.name_en }}
                            </div>
                            <div class="form-group">
                                {{ form.disease_en }}
                            </div>
                            <div class="form-group">
                                {{ form.content_en }}
                            </div>
                            <div class="form-group">
                                <input class="btn btn-dark" type="submit" value="{% trans 'Ավելացնել' %}">
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}