core/urls.py
from django.urls import path
from .views import *


app_name = 'core'

urlpatterns = [
    path('', base, name='base'),
    path('calendar/', calendar, name='calendar'),
    path('info/<int:id>/', info, name='info'),
    path('reviews/', review, name='reviews'),
    path('review/create/', review_create, name='review_create'),
]

xirurgia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


# urlpatterns = [
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
#     path('', include('core.urls')),
#     path('ckeditor/', include('ckeditor_uploader.urls')),
# ]

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=False,
)
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from django.db import models


def validate_only_one_instance(obj):
    model = obj.__class__
    if (model.objects.count() > 0 and
            obj.id != model.objects.get().id):
        raise ValidationError("Դուք կարող եք ստեղծել միայն մեկ" % model.__name__)


class SectionGeneral(models.Model):
    name_hy = models.CharField(max_length=30, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (hy)')
    name_ru = models.CharField(max_length=30, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (ru)')
    name_en = models.CharField(max_length=30, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (en)')
    info_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Պաշտոն և այլն (hy)')
    info_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Պաշտոն և այլն (ru)')
    info_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Պաշտոն և այլն (en)')
    phone = models.CharField(max_length=20, db_index=True, verbose_name='Հեռախոսահամար')
    img = models.ImageField(upload_to='general', verbose_name='Նկար')

    class Meta:
        verbose_name = 'Բժշկի անձնական տվյալներ'
        verbose_name_plural = 'Բժշկի անձնական տվյալներ'

    def __str__(self):
        return self.name_hy

    def clean(self):
        validate_only_one_instance(self)


class GeneralServices(models.Model):
    name_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (hy)')
    name_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (ru)')
    name_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (en)')
    body_hy = RichTextField(max_length=7000, blank=True, verbose_name='Ծառայության մասին (hy)')
    body_ru = RichTextField(max_length=7000, blank=True, verbose_name='Ծառայության մասին (ru)')
    body_en = RichTextField(max_length=7000, blank=True, verbose_name='Ծառայության մասին (en)')
    img = models.ImageField(upload_to='services', verbose_name='Ծառայության նկար')

    class Meta:
        verbose_name = 'Գովազդային ծառայություն'
        verbose_name_plural = 'Գովազդային ծառայություն'

    def __str__(self):
        return self.name_hy

    def clean(self):
        validate_only_one_instance(self)


class Services(models.Model):
    name_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (hy)')
    name_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (ru)')
    name_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Ծառայության անուն (en')
    body_hy = RichTextField(max_length=3000, blank=True, verbose_name='Ծառայության մասին (hy)')
    body_ru = RichTextField(max_length=3000, blank=True, verbose_name='Ծառայության մասին (ru)')
    body_en = RichTextField(max_length=3000, blank=True, verbose_name='Ծառայության մասին (en)')
    img = models.ImageField(upload_to='services', verbose_name='Ծառայության նկար')

    class Meta:
        verbose_name = 'Ծառայություններ'
        verbose_name_plural = 'Ծառայություններ'

    def __str__(self):
        return self.name_hy


class AboutMe(models.Model):
    img = models.ImageField(upload_to='about', verbose_name='Մեր մասին նկար')
    body_l_hy = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (hy) ձախ')
    body_l_ru = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (ru) ձախ')
    body_l_en = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (en) ձախ')
    body_r_hy = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (hy) աջ')
    body_r_ru = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (ru) աջ')
    body_r_en = RichTextField(max_length='3000', blank=True, verbose_name='Մեր մասին տեքստ (en) աջ')

    class Meta:
        verbose_name = 'Բժշկի մասին'
        verbose_name_plural = 'Բժշկի մասին'

    def __str__(self):
        return self.body_l_hy

    def clean(self):
        validate_only_one_instance(self)


class Works(models.Model):
    img = models.ImageField(upload_to='works/%Y/%m/%d', blank=True, verbose_name='Մեր գործերը նկար')
    url = models.CharField(max_length=1000, blank=True, verbose_name='Մեր գործերը լինք')

    class Meta:
        ordering = ['-id']
        verbose_name = 'Կատարված աշխատանք'
        verbose_name_plural = 'Կատարված աշխատանքներ'


class Review(models.Model):
    content_hy = models.TextField(max_length=4000, blank=True, verbose_name='Ակնարկներ (hy)')
    content_ru = models.TextField(max_length=4000, blank=True, verbose_name='Ակնարկներ (ru)')
    content_en = models.TextField(max_length=4000, blank=True, verbose_name='Ակնարկներ (en)')
    name_hy = models.CharField(max_length=40, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (hy)')
    name_ru = models.CharField(max_length=40, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (ru)')
    name_en = models.CharField(max_length=40, blank=True, db_index=True, verbose_name='Անուն Ազգանուն (en)')
    disease_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Բուժված հիվանդությունը (hy)')
    disease_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Բուժված հիվանդությունը (ru)')
    disease_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Բուժված հիվանդությունը (en)')
    published = models.BooleanField(default=False, verbose_name='Հրապարակել')
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Կարծիք'
        verbose_name_plural = 'Կարծիքներ'

    def __str__(self):
        return self.name_hy


class Contacts(models.Model):
    phone = models.CharField(max_length=25, db_index=True, verbose_name='Հեռախոսահամա')
    whatsapp = models.CharField(max_length=30, db_index=True, verbose_name='WhatsApp')
    whatsapp_link = models.CharField(max_length=25, db_index=True, verbose_name='WhatsApp (Առանց '+' և բացատի)')
    viber = models.CharField(max_length=30, db_index=True, verbose_name='Viber')
    viber_link = models.CharField(max_length=25, db_index=True, verbose_name='Viber (Առանց '+' և բացատի)')
    fb = models.CharField(max_length=100, db_index=True, verbose_name='Facebook')
    mail = models.CharField(max_length=50, db_index=True, verbose_name='Mail')
    address_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հասցե (hy)')
    address_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հասցե (ru)')
    address_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հասցե (en)')

    class Meta:
        verbose_name = 'Կոնտակտ'
        verbose_name_plural = 'Կոնտակտներ'

    def __str__(self):
        return self.phone

    def clean(self):
        validate_only_one_instance(self)


class Information(models.Model):
    name_hy = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հիվանդության անունը (hy)')
    name_ru = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հիվանդության անունը (ru)')
    name_en = models.CharField(max_length=100, blank=True, db_index=True, verbose_name='Հիվանդության անունը (en)')
    info_hy = RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (hy)')
    info_ru = RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (ru)')
    info_en = RichTextUploadingField(blank=True, verbose_name='Հիվանդությունների մասին և այլն (en)')

    class Meta:
        verbose_name = 'Հիվանդությունների մասին և այլն'
        verbose_name_plural = 'Հիվանդությունների մասին և այլն'

    def __str__(self):
        return self.name_hy

TIME_CHOICES = [
    ('10:00-10:30', '10:00-10:30'),
    ('10:30-11:00', '10:30-11:00'),
    ('11:00-11:30', '11:00-11:30'),
    ('11:30-12:00', '11:30-12:00'),
    ('12:00-12:30', '12:00-12:30'),
    ('12:30-13:00', '12:30-13:00'),
    ('13:00-13:30', '13:00-13:30'),
    ('13:30-14:00', '13:30-14:00'),
    ('14:00-14:30', '14:00-14:30'),
    ('14:30-15:00', '14:30-15:00'),
    ('15:00-15:30', '15:00-15:30'),
    ('15:30-16:00', '15:30-16:00'),
    ('16:00-16:30', '16:00-16:30'),
    ('16:30-17:00', '16:30-17:00'),
]


class CheckedDate(models.Model):
    date = models.DateField(auto_now_add=False, blank=True, verbose_name='Ամիս ամսաթիվ')

    class Meta:
        verbose_name = 'Աշխատանքային օր'
        verbose_name_plural = 'Աշխատանքային օրեր'

    def __str__(self):
        return str(self.date)

class CheckedTime(models.Model):
    TIME_CHOICES = [
        ('10:00-10:30', '10:00-10:30'),
        ('10:30-11:00', '10:30-11:00'),
        ('11:00-11:30', '11:00-11:30'),
        ('11:30-12:00', '11:30-12:00'),
        ('12:00-12:30', '12:00-12:30'),
        ('12:30-13:00', '12:30-13:00'),
        ('13:00-13:30', '13:00-13:30'),
        ('13:30-14:00', '13:30-14:00'),
        ('14:00-14:30', '14:00-14:30'),
        ('14:30-15:00', '14:30-15:00'),
        ('15:00-15:30', '15:00-15:30'),
        ('15:30-16:00', '15:30-16:00'),
        ('16:00-16:30', '16:00-16:30'),
        ('16:30-17:00', '16:30-17:00'),
    ]
    date = models.ForeignKey('CheckedDate', on_delete=models.CASCADE)
    time = models.CharField(max_length=12, choices=TIME_CHOICES, verbose_name='Ժամ')

    class Meta:
        verbose_name = 'Աշխատանքային ժամ'
        verbose_name_plural = 'Աշխատանքային ժամեր'

    def __str__(self):

core/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from .models import *


class ReviewCreateForm(forms.ModelForm):
    # content = forms.CharField(widget=CKEditorWidget(attrs={'placeholder': '* Ակնարկ'}))

    class Meta:
        model = Review
        fields = ['name_hy', 'disease_hy', 'content_hy', 'name_ru', 'disease_ru', 'content_ru', 'name_en', 'disease_en',
                  'content_en']
        exclude = ['published', 'pub_date']
        widgets = {
            'name_hy': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Անուն Ազգանուն', 'required': ''}),
            'name_ru': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Имя Фамилия', 'required': ''}),
            'name_en': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* First name Last name', 'required': ''}),
            'disease_hy': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Բուժված հիվանդությունը', 'required': ''}),
            'disease_ru': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* Вылеченная болезнь', 'required': ''}),
            'disease_en': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '* The cured disease', 'required': ''}),
            'content_hy': forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'placeholder': '* Ակնարկ'}),
            'content_ru': forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'placeholder': '* Коментария'}),
            'content_en': forms.Textarea(attrs={'class': 'form-control', 'rows': '6', 'placeholder': '* Comment'}),
        }

core/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404
# from bs4 import BeautifulSoup, NavigableString, Tag
from pip._vendor.urllib3.connectionpool import xrange

from .models import *
from .forms import *


def base(request):
    general = SectionGeneral.objects.last()
    service = GeneralServices.objects.last()
    services = Services.objects.all()
    about = AboutMe.objects.last()
    works = Works.objects.all()
    reviews = Review.objects.all()
    contacts = Contacts.objects.last()
    information = Information.objects.all()

    context = {
        'general': general,
        'service': service,
        'services': services,
        'about': about,
        'works': works,
        'reviews': reviews,
        'contacts': contacts,
        'information': information,
    }
    return render(request, 'core/core_base.html', context)


def info(request, id=None):
    general = SectionGeneral.objects.last()
    information = Information.objects.all()
    contacts = Contacts.objects.last()
    info = get_object_or_404(Information, id=id)

    context = {
        'information': information,
        'info': info,
        'contacts': contacts,
        'general': general,
    }
    return render(request, 'core/info.html', context)


def review(request):
    general = SectionGeneral.objects.last()
    information = Information.objects.all()
    contacts = Contacts.objects.last()
    reviews = Review.objects.all()

    context = {
        'information': information,
        'reviews': reviews,
        'contacts': contacts,
        'general': general,
    }
    return render(request, 'core/review.html', context)


def review_create(request):
    general = SectionGeneral.objects.last()
    information = Information.objects.all()
    contacts = Contacts.objects.last()
    if request.method == 'POST':
        form = ReviewCreateForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ReviewCreateForm()

    context = {
        'information': information,
        'review': review,
        'contacts': contacts,
        'general': general,
        'form': form,
    }
    return render(request, 'core/review_create.html', context)



def calendar(request):
    today = datetime.date.today().strftime('%Y-%m-%d')
    tomorrow = datetime.date.today() + datetime.timedelta(days=1)
    tomorrow = tomorrow.strftime('%Y-%m-%d')
    nextYear = int(datetime.date.today().year) + 1
    successDays = CheckedDate.objects.all()
    successTimes = CheckedTime.objects.all()

    weekends = []

    dates = []
    times = []
    for sdays in successTimes:
        dates.insert(0, sdays.date)
        times.insert(0, sdays.time)
    #
    # times = iter(times)
    # dates = iter(dates)
    #
    # res = list(zip(dates, times))
    # data = {}
    # for (x, y) in res:
    #     if x in data:
    #         data[x] = data[x] + y
    #     else:
    #         data[x] = y
    #
    # data = {
    #     'labels': data.keys(),
    #     'default': data.values()
    # }


    # print(data)

    minDate = datetime.date(2020, 1, 1)
    maxDate = datetime.date.today() + datetime.timedelta(days=750)
    daygenerator = (minDate + datetime.timedelta(x + 1) for x in xrange((maxDate - minDate).days))
    for day in daygenerator:
        if day.weekday() >= 5:
            weekends.append(str(day.strftime('%Y-%m-%d')))

    if request.method == 'POST':
        sdate = request.POST.get('date')
        stime = request.POST.get('time')
        if sdate and stime is not None:
            a = CheckedDate.objects.filter(date=sdate)
            print(a.first())
            if a.first() is None:
                createCheckedDate = CheckedDate(date=sdate)
                createCheckedDate.save()
            filteredDate = CheckedDate.objects.filter(date=sdate).first()
            createCheckedTime = CheckedTime(time=stime, date_id=filteredDate.id)
            createCheckedTime.save()
    filteredDate = CheckedDate.objects.all()
    for filtered in filteredDate:
        f_id = filtered.id
        b = len(CheckedTime.objects.filter(date_id=f_id))
        if b == 14:
            f_d = CheckedDate.objects.filter(id=f_id).first()
            weekends.append(f_d)
    choices = []
    for choice in dict(CheckedTime.TIME_CHOICES):
        choices.append(choice)

        # print(stime)
        # print(sdata)

    context = {
        'today': today,
        'tomorrow': tomorrow,
        'successDays': successDays,
        'weekends': weekends,
        'nextYear': nextYear,
        'choices': choices,
    }
    return render(request, 'core/calendar/calendar1.html', context)









templates/core/calendar/calendar1.html
{% load static %}
<!doctype html>
<html lang="hy">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="{% static 'js/datedropper.pro.min.js' %}"></script>
    <title>Document</title>
</head>
<body>
<div class="row justify-content-center">
    <div class="col-6">
        {% for foo in a %}
            {{ foo }}
        {% endfor %}
    </div>
</div>


<form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="row justify-content-center">
        <p>Ընտրել օրը</p>
        <div class="col-4 get-date">
            <a class="btn btn-light get-date-data for-active-class active" id="today" data-date="{{ today }}">Այսօր</a>
            <a class="btn btn-light get-date-data for-active-class" id="tomorrow" data-date="{{ tomorrow }}">Վաղը</a>
            <input type="text" placeholder="Ընտրել օրը" class="btn btn-light get-date-data" id="date-input"
                   data-dd-lang="hy" data-dd-format="Y-m-d" data-dd-min-year="{% now 'Y' %}"
                   data-dd-max-year="{{ nextYear }}"
                   data-dd-modal="true" data-dd-large-only="true"
                   data-dd-disabled-days="{% for foo in weekends %}{{ foo }},{% endfor %}"
                    {#data-dd-disabled-days="01/20/2020,01/21/2020,01/25/2020,01/26/2020"#}
                   data-dd-lock="from"
            >

        </div>
    </div>

    <div class="row justify-content-center">
        <p class="mt-5">Ընտրել ժամը</p>
        <div class="col-4 get-time">
            {% for choice in choices %}
                <a class="btn btn-light get-time-data" data-time="{{choice}}" {% if choices %}
                
                {% endif %} >{{choice}}</a>
            {% endfor %}

{#            <a class="btn btn-light get-time-data active" data-time="10:00-10:30">10:00-10:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="10:30-11:00">10:30-11:00</a>#}
{#            <a class="btn btn-light get-time-data" data-time="11:00-11:30">11:00-11:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="11:30-12:00">11:30-12:00</a>#}
{#            <a class="btn btn-light get-time-data" data-time="12:00-12:30">12:00-12:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="12:30-13:00">12:30-13:00</a>#}
{#            <a class="btn btn-light get-time-data" data-time="13:00-13:30">13:00-13:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="13:30-14:00">13:30-14:00</a>#}
{#            <a class="btn btn-light get-time-data" data-time="14:00-14:30">14:00-14:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="14:30-15:00">14:30-15:00</a>#}
{#            <a class="btn btn-light get-time-data" data-time="15:00-15:30">15:00-15:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="15:30-16:00">15:30-16:00</a>#}
{#            <a class="btn btn-light get-time-data" data-time="16:00-16:30">16:00-16:30</a>#}
{#            <a class="btn btn-light get-time-data" data-time="16:30-17:00">16:30-17:00</a>#}
        </div>

    </div>
    {#    <button id="send">Send Data</button>#}
    <input id="send" type="submit" value="Գրանցվել">


</form>
<script type="text/javascript">
    $('#date-input').dateDropper();

    var $ = jQuery;
    $(document).ready(function () {
        $('.get-time-data').on('click', function (e) {
            var previous = $(this).closest(".get-time").children(".active");
            previous.removeClass('active'); // previous list-item
            $(e.target).addClass('active'); // activated list-item
            var time = $('.get-time').find('.active').data('time');
        });

        $('.get-date-data').on('click', function (e) {
            var previous = $(this).closest(".get-date").children(".active");
            var date_in = new Date($('#date-input').val());
            day = date_in.getDate();
            month = date_in.getMonth() + 1;
            year = date_in.getFullYear();
            previous.removeClass('active'); // previous list-item
            $(e.target).addClass('active'); // activated list-item
            var input_date = $('#date-input').val();

            var date = $('.get-date').find('.active').data('date');

        });
    });
    $("#send").click(function (e) {
        e.preventDefault();

        var date = new Date(document.getElementById("date-input").value);
        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();
        var time = $('.get-time').find('.active').data('time');

        if ($('.for-active-class').hasClass('active')) {
            date = $('.get-date').find('.active').data('date');
        } else {
            if (document.getElementById("date-input").value !== '')
                date = $('#date-input').val();
        }

        


        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        {#$.ajaxSetup({#}
        {#    beforeSend: function (xhr, settings) {#}
        {#        // if not safe, set csrftoken#}
        {#        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {#}
        {#            xhr.setRequestHeader("X-CSRFToken", csrftoken);#}
        {#        }#}
        {#    }#}
        {# });#}

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }

                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    // Only send the token to relative URLs i.e. locally.
                    xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                }
            }
        });

        var ssdata = {
            time: time,
            date: date
        };
        $.ajax({
            type: "post",
            url: "{% url 'core:calendar' %}",
            data: ssdata,
            success: function (data) {
                {#date = ssdata.date;#}
                {#time = ssdata.time;#}
                console.log('Success');
                {#console.log(data)#}
            },
            error: function (errdata) {
                console.log(errdata);
                {#date = ssdata.date;#}
                {#time = ssdata.time;#}
                {#console.log(date);#}
                {#console.log(time);#}
                {#console.log(data);#}
                {#console.log('Error')#}
            }

        });

        {#console.log(ssdata)#}
    });
</script>
{#<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"#}
{#        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"#}
{#        crossorigin="anonymous"></script>#}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>